basePath: /v1
definitions:
  httputil.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
  user.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    required:
    - email
    - username
    type: object
info:
  contact: {}
  description: This is an api Swagger.
  title: Swagger Docs (RESTAPI BoilerPlate)
  version: "1.0"
paths:
  /users:
    get:
      description: Returning list of users
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/httputil.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/user.User'
                  type: array
              type: object
      summary: List Users
      tags:
      - Users
    post:
      description: Create New User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.Response'
      summary: Create User
      tags:
      - Users
  /users/{userId}:
    get:
      description: Returning an user with given id
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/httputil.Response'
            - properties:
                data:
                  $ref: '#/definitions/user.User'
              type: object
      summary: Users by Id
      tags:
      - Users
swagger: "2.0"
